from enum import Enum

class Label(Enum):
    PCP = 'PCP',
    PDEN = 'PDEN',
    CUR = 'CUR',
    PREP = 'PREP',
    PREP__PROSUB = 'PREP+PROSUB',
    KS = 'KS',
    ADV_KS = 'ADV-KS',
    PREP__ADV = 'PREP+ADV',
    PRO_KS = 'PRO-KS',
    NUM = 'NUM',
    PROSUB = 'PROSUB',
    ADV = 'ADV',
    PROADJ = 'PROADJ',
    NPROP = 'NPROP',
    PU = 'PU',
    PROPESS = 'PROPESS',
    PREP__ART = 'PREP+ART',
    ADJ = 'ADJ',
    V = 'V',
    N = 'N',
    ART = 'ART',
    PREP__PROPESS = 'PREP+PROPESS',
    IN = 'IN',
    PREP__PRO_KS = 'PREP+PRO-KS',
    PREP__PROADJ = 'PREP+PROADJ',
    KC ='KC'

